### PR TITLE
#161133714 Store admin can view all sales record while attendant can view his sales record

### PR DESCRIPTION
**Pull request by iMichaelOwolabi**
#### What does this PR do?
To review the changes made to sales page
#### Description of Task to be completed?
To get this branch merged ultimately to the develop branch after acceptance
#### How should this be manually tested?
This can be tested out by visiting https://imichaelowolabi.github.io/store-manager/UI/sales.html after acceptance or referring the attached screenshot
#### Any background context you want to provide?
There are different sales record page for admin and attendants before now. In the new design the two pages has been brought under one page and rendered according the login user
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2203575
#### Screenshots (if appropriate)
sales

#### Questions:
Are there things I should change/edit?

### CODE REVIEW

**Comment by amarachukwu-agbo** [comment]
@iMichaelOwolabi What is the difference between your sales record and the store sales record?

**Comment by amarachukwu-agbo** [comment]
Why is the branch to be merged into 'feature' instead of 'develop'?

**Comment by amarachukwu-agbo** [comment]
Why do you have two PT story ids in the branch name?

**Comment by iMichaelOwolabi** [comment]
What is the difference between your sales record and the store sales record?
<b>Response:</b> Your sales record is what is displayed when attendants login, but when an admin logs in Store sales record will be displayed instead.

Why is the branch to be merged into 'feature' instead of 'develop'?
<b>Response:</b> I am merging intermittently from feature to develop. I created the branch off feature branch

Why do you have two PT story ids in the branch name?
<b>Response:</b> Because before now, I have two different pages and two different user stories on PT. But now the two pages is are being made one. That is the reason I link the two user stories to the PR.

Thanks

**Comment by amarachukwu-agbo** [comment]
The sales record explanation makes sense. Just remove the 'Below is your ....' for both the admin and attendant. A simple heading like 'Your Sales Record' and 'Store Sales Record' will do.
Find a way to combine the two stories into one. It should be only one story id.

**Pull request merged**
